networks:
  trading-network:
    driver: bridge
services:
  kafka1:
    container_name: kafka1
    image: 'bitnami/kafka:latest'
    networks:
      - trading-network
    ports:
      - '9192:9092'
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.25:9192
      - KAFKA_HEAP_OPTS=-Xmx1g -Xms1g
      - TZ=Asia/Shanghai
    volumes:
      - ./kafka/k1:/bitnami/kafka
  kafka2:
    container_name: kafka2
    image: 'bitnami/kafka:latest'
    networks:
      - trading-network
    ports:
      - '9292:9092'
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.25:9292
      - KAFKA_HEAP_OPTS=-Xmx1g -Xms1g
      - TZ=Asia/Shanghai
    volumes:
      - ./kafka/k2:/bitnami/kafka
  kafka3:
    container_name: kafka3
    image: 'bitnami/kafka:latest'
    networks:
      - trading-network
    ports:
      - '9392:9092'
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.25:9392
      - KAFKA_HEAP_OPTS=-Xmx1g -Xms1g
      - TZ=Asia/Shanghai
    volumes:
      - ./kafka/k3:/bitnami/kafka
  mysql:
    container_name: mysql
    image: 'bitnami/mysql:latest'
    networks:
      - trading-network
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=GewMxiNfOtgdaPd7
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_bin
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql:/bitnami/mysql
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    networks:
      - trading-network
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=GewMxiNfOtgdaPd7
      - TZ=Asia/Shanghai
    volumes:
      - ./redis:/bitnami/redis